name: CI Pipeline - Cold Storage App

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # =========================
      # BACKEND SETUP
      # =========================
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Backend
        working-directory: ./backend
        run: nohup npm start &

      # =========================
      # FRONTEND SETUP
      # =========================
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Start Frontend
        working-directory: ./frontend
        run: nohup npm run preview &

      # =========================
      # PLAYWRIGHT SETUP
      # =========================
      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: ./frontend
        run: npm run test:e2e